name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch to deploy the pages to
          folder: _site # The folder where the built pages are located
          token: ${{ secrets.GITHUB_TOKEN }} # The token to authenticate the deployment
